import {encounter} from './waves.js';
import {WORLDS,terrainAt,navigation} from './world.js';
import {BattleCore} from './core.js';
import {BattleView} from './view.js';
import {loadArt,portraitDataURL} from './art.js';
import {createInput} from './input.js';
import {CHARACTERS,REGIONS,WEAPONS,PASSIVES,CONSUMABLES,SOURCES,SWORD_COUNTS,ENEMIES} from './catalog.js';
import {GameAudio} from './audio.js';
import {registerGameTools} from './webmcp.js';
import {menuFigureDataURL,titleMarkup,installTitleNavigation} from './menu.js';
import {upgradeDetails} from './upgrade-copy.js';
import {radarTarget,radarObjective,paintRadarTile,drawRadar} from './radar.js';

const $=id=>document.getElementById(id), RUN='qingzhu-human-run-v2', META='qingzhu-human-meta-v2';
const storage={get(k){try{return localStorage.getItem(k);}catch{return null;}},set(k,v){try{localStorage.setItem(k,v);return true;}catch{return false;}},remove(k){try{localStorage.removeItem(k);}catch{}}};
function loadMeta(){try{return{cleared:0,hpRank:0,pickupRank:0,coins:0,discoveries:[],claims:[],...JSON.parse(storage.get(META)||'{}')};}catch{return{cleared:0,hpRank:0,pickupRank:0,coins:0,discoveries:[],claims:[]};}}
let meta=loadMeta(),g=new BattleCore({meta}),view,art,input,selected='hanli',screen='',lastMode='',loadoutKey='',saveClock=0,hudClock=0,bagSlot=0,backScreen='title',saveWarning=false;
const audio=new GameAudio();audio.enabled=storage.get('qingzhu-sound')!=='off';
const portraits={},menuFigures={},timeLabel=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
function toast(text,special=false){if(special&&screen==='title')return;const el=document.createElement('div');el.className='toast'+(special?' special':'');el.textContent=text;$('toasts').append(el);while($('toasts').children.length>2)$('toasts').firstElementChild.remove();setTimeout(()=>el.remove(),3500);}
function saveMeta(){storage.set(META,JSON.stringify(meta));}
function saveRun(){if(['title','won','lost'].includes(g.mode))return;meta.cleared=Math.max(meta.cleared,g.meta.cleared);meta.discoveries=[...new Set([...meta.discoveries,...g.discoveries])];saveMeta();if(!storage.set(RUN,g.save())&&!saveWarning){saveWarning=true;toast('浏览器未能保存进度，请保持此页面打开');}}
function claim(){if(meta.claims.includes(g.claimId))return;const won=g.mode==='won';const reward=Math.floor(g.player.spirit*(won?1:.3));meta.coins+=reward;meta.cleared=Math.max(meta.cleared,g.meta.cleared);meta.discoveries=[...new Set([...meta.discoveries,...g.discoveries,...Object.keys(g.player.weapons)])];meta.claims.push(g.claimId);meta.claims=meta.claims.slice(-50);g.rewardClaimed=true;saveMeta();storage.remove(RUN);return reward;}
function button(label,action,cls='secondary',disabled=false){return `<button class="${cls}" data-action="${action}" ${disabled?'disabled':''}>${label}</button>`;}
function panel(content,cls=''){return `<section class="panel ${cls}">${content}</section>`;}
function modal(html,name){if(name!=='title')$('toasts').querySelectorAll('.special').forEach(el=>el.remove());if(screen==='title'&&name!=='title')$('toasts').replaceChildren();screen=name;lastMode=g.mode;const el=$('modal');el.dataset.screen=name;el.classList.toggle('menu-context',name==='title'||(backScreen==='title'&&['settings','codex','meta','newconfirm','characterinfo'].includes(name)));el.innerHTML=html;el.classList.remove('hidden');}
function hideModal(){screen='';$('modal').classList.add('hidden');$('modal').innerHTML='';input?.reset();}
function returnToMenu(){saveRun();g=new BattleCore({character:selected,meta});lastMode='';$('hud').classList.add('hidden');showTitle();}
function startNew(){audio.unlock();g=new BattleCore({character:selected,meta});g.start();lastMode='';loadoutKey='';saveClock=0;hideModal();$('hud').classList.remove('hidden');$('hud-portrait').src=portraits[g.character];saveRun();}
function continueRun(){try{const saved=storage.get(RUN);g=BattleCore.load(saved);if(JSON.parse(saved).version===4&&!storage.get(RUN+'-before-world-rework'))storage.set(RUN+'-before-world-rework',saved);if(g.mode==='paused')g.mode='playing';selected=g.character;lastMode='';loadoutKey='';hideModal();$('hud').classList.remove('hidden');$('hud-portrait').src=portraits[g.character];audio.unlock();syncMode();}catch{toast('这份存档无法读取，可重新开始试炼');}}
function showTitle(){
 $('toasts').replaceChildren();
 let saved=null;try{if(storage.get(RUN))saved=BattleCore.load(storage.get(RUN));}catch{}
 modal(titleMarkup({selected,meta,figures:menuFigures,saved,timeLabel}),'title');
}
function showCharacterInfo(){const c=CHARACTERS[selected];modal(panel(`<p class="eyebrow">此行之人</p><div class="character-detail"><img src="${portraits[selected]}" alt="${c.name}像素形象"><div><h2>${c.name}</h2><p class="subline">${c.epithet}</p><p class="description">${c.description}</p><p class="subline">起始法器 · ${c.starter==='sword'?'飞剑':WEAPONS[c.starter].name}<br>角色法术 · ${c.skill}</p></div></div><div class="button-row">${button('返回','back')}</div>`),'characterinfo');}
function pause(){if(g.mode==='playing'){g.pause();saveRun();showPause();}else if(g.mode==='paused'){g.pause();hideModal();}else if(screen==='settings'||screen==='codex'||screen==='meta')back();}
function showChallenge(){g.pause();modal(panel(`<h2>提前挑战首领</h2><p class="description">五息后引来本境首领，跳过的敌潮和材料奖励不会补发。击败首领即可从界门离境，也可留下继续探索。</p><div class="button-row">${button('引来首领','challenge','primary')}${button('继续积累','resume')}</div>`),'challenge');}
function showPause(){modal(panel(`<div class="eyebrow">暂歇片刻</div><h2>凝神调息</h2><p class="description">${g.region.name} · ${timeLabel(g.time)} · ${g.realm} · 修为${g.player.level}</p><p class="subline">已记录当前试炼进度。</p><div class="button-row">${button('继续修行','resume','primary')}${button('查看行囊','bag')}${button('设置','settings')}${button('存档并返回','title')}</div>`),'pause');}
function showUpgrade(){modal(panel(`<div class="upgrade-heading"><div><h2>突破 · ${g.realm} · 修为${g.player.level}</h2></div><small>三选其一 · 修行暂停</small></div><div class="upgrade-grid">${g.upgrades.map((u,i)=>{const def=u.type==='weapon'?WEAPONS[u.id]:u.type==='passive'?PASSIVES[u.id]:{name:u.id==='heal'?'回春灵药':'灵石补给',icon:u.id==='heal'?'药':'石'},copy=upgradeDetails(g,u);return `<button class="upgrade-card" data-upgrade="${i}"><span class="type">${u.type==='weapon'?def.type:u.type==='passive'?'功法':'补给'} · ${u.owned?`精进 ${u.rank-1}→${u.rank} 重`:u.type==='supply'?'即刻生效':'新学'}</span><kbd>${i+1}</kbd><h3>${u.id==='sword'&&!g.player.swordCrafted?'飞剑 · 御剑术':def.name}</h3><p class="upgrade-delta">${copy.headline}</p><p>${copy.detail}</p>${copy.synergy?`<small class="upgrade-synergy">${copy.synergy}</small>`:''}<small class="upgrade-synergy">${copy.slot}</small></button>`;}).join('')}</div><p class="upgrade-bottom">攻击法门已占 ${Object.keys(g.player.weapons).length}/4 · 功法已占 ${Object.keys(g.player.passives).length}/4。新学占一槽，精进不占新槽。</p>`,'upgrade-panel'),'upgrade');}
function chooseUpgrade(i){if(g.chooseUpgrade(i)){hideModal();lastMode='';saveRun();syncMode();return true;}return false;}
function showEvent(){const poi=g.pois.find(p=>p.id===g.currentEvent);modal(panel(`<p class="eyebrow">境中机缘</p><h2>${poi?.name||'驻足'}</h2><p class="subline">灵石 ${g.player.spirit} · 金雷竹 ${g.player.materials.bamboo} · 庚精 ${g.player.materials.gold}${g.character==='hanli'?' · 绿液 '+g.player.greenLiquid:''}</p><div class="event-options">${g.eventOptions().map(o=>`<button class="event-option" data-event="${o.id}" ${o.disabled?'disabled':''}><strong>${o.name}</strong><span>${o.description}</span></button>`).join('')}</div><div class="button-row">${button('暂且离开','leave')}</div>`),'event');}
function showTransition(){saveRun();warmRegion(g.regionIndex+1);modal(panel(`<p class="eyebrow">第${g.regionIndex+1}境 · 已过</p><h2>${REGIONS[g.regionIndex+1].name}</h2><p class="description">${g.regionIndex===0?'越过禁地，海天在前。更强的妖兽守着庚精，也守着飞剑进阶的机缘。':'踏入古殿，玄骨已在深处等候。积累修为、补足灵材，决定最后的御敌之法。'}</p><p class="subline">${g.regionIndex===0?'南宫婉':'银月'}已解锁，下次开局可选。跨境恢复35生命与全部灵力。</p><div class="button-row">${button('踏入下一境','next','primary')}${button('存档并返回','title')}</div>`),'transition');}
function showResult(){const won=g.mode==='won',reward=claim();modal(panel(`<p class="eyebrow">${won?'人界三境 · 试炼已成':'此番止步 · 修行未尽'}</p><h2>${won?'剑起人间':'来日再入凡尘'}</h2><p class="description">${won?'走过禁地、乱星海与虚天殿，这一局的修行已圆满。':'机缘已记入图鉴。带着这一程的收获，换一条修行路再试。'}</p><div class="stats-row"><div class="stat"><b>${timeLabel(g.time)}</b><span>修行时长</span></div><div class="stat"><b>${g.kills}</b><span>斩妖数量</span></div><div class="stat"><b>${g.player.level}</b><span>修为层数</span></div></div><p class="subline">带回${reward??Math.floor(g.player.spirit*(won?1:.3))}灵石 · ${won?'保留全部灵石':'保留三成灵石'} · 图鉴与角色解锁保留</p><div class="button-row">${button('再入一境','retry','primary')}${button('返回洞府','title')}</div>`),'result');}
function showBag(){if(g.mode==='playing'){g.pause();saveRun();}if(g.mode!=='paused')return;const p=g.player;modal(panel(`<p class="eyebrow">随身行囊</p><h2>法器与符箓</h2><p class="subline">灵石 ${p.spirit} · 金雷竹 ${p.materials.bamboo} · 庚精 ${p.materials.gold}${g.character==='hanli'?' · 绿液 '+p.greenLiquid:''}</p><div class="bag-section"><h3>快捷符箓 · 点击物品装入选中栏</h3><div class="quick-select">${p.quick.map((id,i)=>`<button data-slot="${i}" class="${bagSlot===i?'selected':''}">${i+1} · ${CONSUMABLES[id].name}</button>`).join('')}</div><div class="bag-grid" style="margin-top:12px">${Object.entries(CONSUMABLES).map(([id,v])=>`<button data-consumable="${id}"><b>${v.name} × ${p.consumables[id]}</b><small>${v.description}</small></button>`).join('')}</div></div><div class="bag-section"><h3>本局法门</h3><p class="description">${Object.entries(p.weapons).map(([id,r])=>`${id==='sword'&&!p.swordCrafted?'飞剑（未炼青竹）':WEAPONS[id].name} ${id==='sword'?g.swordCount+'口':r+'重'}`).join(' · ')}<br>${Object.entries(p.passives).map(([id,r])=>`${PASSIVES[id].name} ${r}重`).join(' · ')||'尚未习得辅助功法'}</p></div><p class="subline">${p.arrayType==='sword'?'大庚剑阵':'颠倒五行阵'} · 在三个位置布旗，消耗15灵石成阵。长按 F 回收。</p><div class="button-row">${button('收起行囊','resume','primary')}${button('修行图鉴','codex')}</div>`),'bag');}
function showCodex(){modal(panel(`<p class="eyebrow">器物有来处 · 修行由你定</p><h2>修行图鉴</h2><p class="description">取材于《凡人修仙传》的非官方同人游戏。角色与器物跨时段组合，攻击数值、通关次序与成长系统均为游戏改编。</p><div class="codex-scroll">${[...Object.entries(WEAPONS),...Object.entries(PASSIVES)].map(([id,v])=>`<article class="codex-entry"><h3>${v.name} <small>${meta.discoveries.includes(id)?'· 已见':'· 待遇'}</small></h3><p>${v.description}</p></article>`).join('')}<article class="codex-entry"><h3>原著资料</h3><p>小瓶催熟、法宝炼制与阵旗布阵是改编依据。其他角色使用灵圃培养，不持有韩立的小瓶。人物外形以本项目提供的动漫参考为准。</p>${SOURCES.map(s=>`<a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.label} ↗</a><br>`).join('')}</article></div><div class="button-row">${button('返回','back')}</div>`),'codex');}
function showMeta(){modal(panel(`<p class="eyebrow">歇脚之处</p><h2>洞府</h2><p class="description">带回灵石 ${meta.coins}。仅能略增体魄与拾取范围，每次试炼仍从一件法器开始。</p><div class="settings-row"><span>温养体魄 · ${meta.hpRank}/2 · 每次生命+5%</span>${button(`80灵石 · 温养`,'buyhp','secondary',meta.hpRank>=2||meta.coins<80)}</div><div class="settings-row"><span>凝神寻物 · ${meta.pickupRank}/3 · 每次拾取范围+5%</span>${button('60灵石 · 凝神','buypickup','secondary',meta.pickupRank>=3||meta.coins<60)}</div><p class="description">韩立 · 初始可选<br>南宫婉 · ${meta.cleared>=1?'已解锁':'通过血色禁地解锁'}<br>银月 · ${meta.cleared>=2?'已解锁':'通过乱星海解锁'}</p><div class="button-row">${button('返回','back')}</div>`),'meta');}
function showSettings(){modal(panel(`<p class="eyebrow">随心调息</p><h2>设置</h2><div class="settings-layout"><div class="settings-switches"><div class="settings-row"><span>战斗音效</span>${button(audio.enabled?'已开启':'已关闭','sound')}</div><div class="settings-row"><span>粒子与伤害数字</span>${button(view.reduced?'简化':'完整','effects')}</div><div class="settings-row"><span>全屏战斗</span>${button(document.fullscreenElement?'退出全屏':'进入全屏','fullscreen')}</div></div><div class="settings-controls"><p class="description">WASD / 方向键移动，自动攻击<br>Space 闪避 · E 角色法术<br>F 布阵 / 长按回收 · R 交互<br>Q 用符 · 1/2 切换符箓<br>Tab 行囊 · P 暂停</p><p class="subline">手机横屏，左摇杆移动，右侧施法。<br>切走页面会自动暂停并存档。</p></div></div><div class="button-row">${button('返回','back')}</div>`,'settings-panel'),'settings');}
function back(){if(backScreen==='title')showTitle();else if(backScreen==='bag')showBag();else showPause();}
function syncMode(){if(g.mode===lastMode)return;lastMode=g.mode;if(g.mode==='playing')hideModal();else if(g.mode==='upgrade')showUpgrade();else if(g.mode==='event')showEvent();else if(g.mode==='transition')showTransition();else if(g.mode==='won'||g.mode==='lost')showResult();else if(g.mode==='paused')showPause();}
installTitleNavigation(()=>screen);
$('modal').addEventListener('click',async e=>{
 const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.dataset.character){const id=b.dataset.character;if(meta.cleared<CHARACTERS[id].unlock){toast(`通过第${CHARACTERS[id].unlock}境后解锁${CHARACTERS[id].name}`);return;}selected=id;g=new BattleCore({character:id,meta});showTitle();return;}
 if(b.dataset.upgrade!==undefined){chooseUpgrade(Number(b.dataset.upgrade));return;}
 if(b.dataset.event){g.chooseEvent(b.dataset.event);hideModal();lastMode='';saveRun();syncMode();return;}
 if(b.dataset.slot!==undefined){bagSlot=Number(b.dataset.slot);showBag();return;}
 if(b.dataset.consumable){g.player.quick[bagSlot]=b.dataset.consumable;g.player.quickIndex=bagSlot;saveRun();showBag();return;}
 const action=b.dataset.action;
 if(action==='start'){if(storage.get(RUN)){modal(panel(`<h2>重新入境</h2><p class="description">新试炼会替换这份未完成的进度。角色解锁与洞府修行保留。</p><div class="button-row">${button('开始新试炼','newconfirmed','primary')}${button('保留并返回','cancelenew')}</div>`),'newconfirm');}else startNew();}
 if(action==='newconfirmed'||action==='retry')startNew();if(action==='cancelenew')showTitle();if(action==='continue')continueRun();
 if(action==='challenge'){g.mode='playing';g.challengeBoss();lastMode='';hideModal();saveRun();}
 if(action==='resume'){g.mode='playing';lastMode='';hideModal();audio.unlock();}
 if(action==='title')returnToMenu();if(action==='bag')showBag();if(action==='leave'){g.chooseEvent('leave');hideModal();lastMode='';}
 if(action==='next'){await warmRegion(g.regionIndex+1);g.nextRegion();hideModal();lastMode='';saveRun();}
 if(action==='characterinfo'){backScreen='title';showCharacterInfo();}
 if(['settings','codex','meta','help'].includes(action)){backScreen=screen;({settings:showSettings,codex:showCodex,meta:showMeta,help:showSettings})[action]();}
 if(action==='back')back();if(action==='sound'){audio.toggle();storage.set('qingzhu-sound',audio.enabled?'on':'off');showSettings();}
 if(action==='effects'){view.reduced=!view.reduced;storage.set('qingzhu-effects',view.reduced?'low':'full');showSettings();}
 if(action==='fullscreen'){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('此浏览器暂不支持全屏');}showSettings();}
 if(action==='buyhp'&&meta.hpRank<2&&meta.coins>=80){meta.coins-=80;meta.hpRank++;saveMeta();showMeta();}
 if(action==='buypickup'&&meta.pickupRank<3&&meta.coins>=60){meta.coins-=60;meta.pickupRank++;saveMeta();showMeta();}
});
function updateHUD(){
 const p=g.player,c=CHARACTERS[g.character];$('hud-name').textContent=c.name;$('realm').textContent=`${g.realm} · 修为${p.level}`;$('hp-fill').style.width=`${100*p.hp/p.maxHp}%`;$('hp-label').textContent=`${Math.ceil(p.hp)} / ${Math.ceil(p.maxHp)}${p.shield?' +'+Math.ceil(p.shield):''}`;$('mana-fill').style.width=`${100*p.mana/p.maxMana}%`;$('mana-label').textContent=`${Math.floor(p.mana)} / ${p.maxMana}`;$('xp-fill').style.width=`${Math.min(100,p.xp/p.xpNext*100)}%`;
 $('region-name').textContent=WORLDS[g.regionIndex].title;$('clock').textContent=timeLabel(g.time);$('stage-progress').textContent=`${encounter(g.regionIndex,g.regionTime).name} · 斩妖 ${g.kills}`;$('coin-label').textContent=`灵石 ${p.spirit}`;
 const boss=g.enemies.find(e=>e.boss&&e.hp>0);$('boss-bar').classList.toggle('hidden',!boss);if(boss){$('boss-name').textContent=boss.name+(boss.guard?(boss.bossPhase==='recover'?' · 破绽 · 伤害↑':' · 护体 · 伤害↓'):'');$('boss-fill').style.width=`${Math.max(0,boss.hp/boss.maxHp)*100}%`;}
 const mapFocus=radarTarget(g,boss);$('objective').textContent=radarObjective(g,mapFocus);
 $('challenge-boss').classList.toggle('hidden',!g.canChallengeBoss);$('challenge-boss').disabled=g.mode!=='playing';
 $('encounter-hint').textContent=g.bossDead?'界门已开 · 可离境或继续探索':boss?'躲开蓄力范围，趁收招攻击':g.canChallengeBoss?`首领还有 ${timeLabel(g.region.bossAt-g.regionTime)} · 准备好可提前挑战`:`首领还有 ${timeLabel(Math.max(0,g.region.bossAt-g.regionTime))}`;
 const key=JSON.stringify([p.weapons,p.passives,p.swordCrafted]);if(key!==loadoutKey){loadoutKey=key;const weapons=Object.entries(p.weapons),passives=Object.entries(p.passives);$('loadout').innerHTML=Array.from({length:4},(_,i)=>{const [id,r]=weapons[i]||[];return `<div class="weapon-slot ${id?'':'empty'}" title="${id?WEAPONS[id].name:'空法器位'}"><b>${id?WEAPONS[id].icon:'·'}</b><small>${id?WEAPONS[id].short:''}</small><em>${id==='sword'?g.swordCount:r||''}</em></div>`;}).join('')+`<div class="passive-slots">${Array.from({length:4},(_,i)=>{const [id,r]=passives[i]||[];return `<div class="weapon-slot ${id?'':'empty'}" title="${id?PASSIVES[id].name:'空功法位'}"><b>${id?PASSIVES[id].icon:'·'}</b><em>${r||''}</em></div>`;}).join('')}</div>`;}
 $('skill-name').textContent=c.skill;for(const [id,remaining,total]of[['dash',p.dash,2.7],['skill',p.skill,10]]){$(id).classList.toggle('cooldown',remaining>0);$(id).querySelector('i').style.clipPath=`inset(${100*(1-remaining/total)}% 0 0 0)`;}
 $('flag-label').textContent=g.array?`${g.array.kind==='sword'?'剑阵':'五行阵'} ${Math.ceil(g.array.duration-g.array.age)}息`:g.flags.length?`已布 ${g.flags.length}/3 · 长按回收`:'布阵 / 回收';
 const item=p.quick[p.quickIndex];$('item-name').textContent=CONSUMABLES[item].name;$('item-icon').textContent=CONSUMABLES[item].icon;$('item-count').textContent=p.consumables[item];
 const poi=g.nearestPOI(),near=poi&&Math.hypot(poi.x-p.x,poi.y-p.y)<72;$('interact').classList.toggle('hidden',!near||g.mode!=='playing');if(near)$('interact').textContent=`${poi.name} · R`;$('tutorial').style.opacity=g.time<45?'1':'.35';drawMap(mapFocus);
}
const mapBackgrounds=new Map();
function mapBackground(region,cx,cy){const key=`${region}:${cx}:${cy}`;if(!mapBackgrounds.has(key)){if(mapBackgrounds.size>=36)mapBackgrounds.delete(mapBackgrounds.keys().next().value);mapBackgrounds.set(key,paintRadarTile(document.createElement('canvas'),terrainAt,region,cx,cy));}return mapBackgrounds.get(key);}
function drawMap(focus){const canvas=$('minimap');drawRadar(canvas.getContext('2d'),g,(cx,cy)=>mapBackground(g.regionIndex,cx,cy),focus);const label=`玩家居中的附近地形雷达；${radarObjective(g,focus)}`;if(canvas.getAttribute('aria-label')!==label)canvas.setAttribute('aria-label',label);}
async function warmRegion(index){const radii=new Set([11,20,...REGIONS[index].enemy.flatMap(id=>[ENEMIES[id].r,ENEMIES[id].r*1.25]),ENEMIES[REGIONS[index].boss].r]);for(const radius of radii){navigation(index,radius);await new Promise(requestAnimationFrame);}}
async function boot(){try{
 art=await loadArt((n,total)=>{$('load-fill').style.width=`${n/total*100}%`;$('load-message').textContent=`载入山川人物 · ${n}/${total}`;});for(const id of Object.keys(CHARACTERS)){portraits[id]=portraitDataURL(art,id);menuFigures[id]=menuFigureDataURL(art,id);}$('load-message').textContent='推演山川通路';await warmRegion(0);view=await new BattleView($('scene'),art).init();
 input=createInput({onPause:pause,onBag:()=>{if(screen==='bag'){g.mode='playing';lastMode='';hideModal();}else showBag();},onBlur:()=>{if(g.mode==='playing'){g.pause();saveRun();lastMode='';syncMode();}},onUpgrade:i=>g.mode==='upgrade'?chooseUpgrade(i):false});$('challenge-boss').onclick=()=>{if(g.mode==='playing'&&g.canChallengeBoss)showChallenge();};$('pause-button').onclick=pause;$('bag-button').onclick=showBag;addEventListener('pagehide',saveRun);$('loading').classList.add('hidden');showTitle();
 registerGameTools({read:()=>g.snapshot(),start:()=>{if(!['title','won','lost'].includes(g.mode)||storage.get(RUN))throw Error('已有未完成试炼，请从画面继续');startNew();},pause:desired=>{if(!['playing','paused'].includes(g.mode))throw Error('请先完成当前选择');if((g.mode==='paused')!==desired)pause();},choose:chooseUpgrade});
 let last=performance.now(),acc=0;const perf=[];
 function frame(now){const wall=(now-last)/1000;last=now;const dt=Math.min(.1,wall);perf.push(wall*1000);if(perf.length>900)perf.shift();acc+=dt;let controls,steps=0;while(acc>=1/60&&steps<6){if(steps===0)controls=input.read();g.tick(1/60,controls);controls={x:controls.x,y:controls.y};acc-=1/60;steps++;}const events=g.drainEvents();view.consume(events);audio.consume(events);for(const e of events){if(e.type==='notice')toast(e.text);if(e.type==='evolution')toast(e.text,true);if(e.type==='boss')toast(`${e.name}现身 · 依地图寻踪`,true);if(e.type==='region')toast(e.name,true);}syncMode();view.update(g,g.mode==='playing'?dt:0);hudClock+=dt;if(hudClock>.1){updateHUD();hudClock=0;}if(g.mode==='playing'){saveClock+=dt;if(saveClock>10){saveClock=0;saveRun();}}requestAnimationFrame(frame);}
 if(['localhost','127.0.0.1'].includes(location.hostname))Object.defineProperty(window,'qingzhuQA',{value:Object.freeze({read(){const sorted=perf.slice().sort((a,b)=>a-b);return JSON.parse(JSON.stringify({...g.snapshot(),player:g.player,pois:g.pois,pickups:g.pickups,targets:g.enemies.map(e=>({id:e.id,kind:e.kind,x:e.x,y:e.y,hp:e.hp,boss:e.boss,windup:e.windup,dx:e.dx,dy:e.dy,r:e.r,age:e.age,atlas:e.atlas,row:e.row,moving:e.moving,facing:e.facing,action:e.action,charge:e.charge,bossPhase:e.bossPhase,attackKind:e.attackKind,attackCount:e.attackCount})),projectiles:g.projectiles.filter(q=>q.owner==='enemy'),hazards:g.hazards,flags:g.flags,array:g.array,screen,frameMS:{p50:sorted[Math.floor(sorted.length*.5)]||0,p95:sorted[Math.floor(sorted.length*.95)]||0},art:Object.fromEntries(Object.entries(art).map(([id,s])=>[id,{width:s.width,height:s.height,frames:s.frames.flat().length}]))}));}})});
 requestAnimationFrame(frame);
 }catch(error){console.error(error);$('load-message').innerHTML='载入失败，请刷新重试。';const b=document.createElement('button');b.textContent='重新载入';b.className='secondary';b.onclick=()=>location.reload();$('loading').append(b);}}
boot();
