import test from 'node:test';
import assert from 'node:assert/strict';
import {BattleCore} from '../src2d/core.js';
import {WEAPONS,SWORD_COUNTS} from '../src2d/catalog.js';
import {updateWeapons,updateSwords,useConsumable} from '../src2d/combat.js';
const game=()=>{const g=new BattleCore({seed:123});g.start();g.drainEvents();return g;};
test('fresh run owns exactly one sword; high meta never grants more',()=>{const g=new BattleCore({meta:{hpRank:99,pickupRank:99,cleared:3}});g.start();assert.equal(g.swords.length,1);assert.equal(g.player.weapons.sword,1);assert.equal(g.player.maxHp,121.00000000000001);});
test('all eight sword ranks conserve the entity pool during array placement and recall',()=>{for(let rank=1;rank<=8;rank++){const g=game();g.player.weapons.sword=rank;g.syncSwords();assert.equal(g.swords.length,SWORD_COUNTS[rank-1]);g.player.arrayRecipe=true;g.player.arrayType='sword';g.player.x=0;g.player.y=0;g.placeFlag();g.player.x=130;g.placeFlag();g.player.y=130;g.placeFlag();assert.ok(g.array);assert.equal(g.swords.length,g.swordCount);const reserved=g.swords.filter(s=>s.mode==='array').length;assert.equal(reserved,g.swordCount>=36?Math.ceil(g.swordCount/3):0);g.recallArray();assert.equal(g.swords.filter(s=>s.mode==='array').length,0);assert.equal(g.swords.length,g.swordCount);}});
test('invalid triangle and insufficient spirit cannot create a paid formation',()=>{const g=game();g.player.x=g.player.y=0;g.placeFlag();g.player.x=60;g.placeFlag();g.player.x=120;assert.equal(g.placeFlag(),false);assert.equal(g.array,null);assert.equal(g.player.spirit,30);g.recallArray();g.player.spirit=14;assert.equal(g.placeFlag(),false);});
test('one sword hit is a single damage event, not multiplied by a visual trail',()=>{const g=game();const e=g.spawn('ape',80,110);g.hash.rebuild(g.enemies);const s=g.swords[0];s.mode='attack';s.target=e.id;s.life=1;s.x=74;s.y=110;const before=e.hp;updateSwords(g,1/60);assert.equal(before-e.hp,21);assert.equal(s.mode,'return');});
test('every non-sword weapon produces its own attack or field and affects a target',()=>{for(const id of Object.keys(WEAPONS).filter(x=>x!=='sword')){const g=game();g.player.weapons={[id]:3};g.swords=[];const e=g.spawn('ape',g.player.x+100,g.player.y);g.hash.rebuild(g.enemies);g.weaponClocks[id]=0;updateWeapons(g,.02);assert.ok(g.projectiles.length||g.zones.length||e.hp<e.maxHp,id);}});
test('save reload retains RNG, entities, equipment, world events and active choices',()=>{const g=game();for(let i=0;i<120;i++)g.tick(1/30,{x:1,y:0});g.openUpgrades();g.drainEvents();const loaded=BattleCore.load(g.save());assert.deepEqual(loaded.snapshot(),g.snapshot());assert.deepEqual(loaded.player,g.player);assert.deepEqual([...loaded.pois].sort((a,b)=>a.id-b.id),[...g.pois].sort((a,b)=>a.id-b.id));assert.equal(loaded.random(),g.random());});
test('paused, inventory and upgrade choices never advance battle time',()=>{const g=game();g.pause();const before=g.save();g.tick(.05,{x:1,skill:true});assert.equal(g.save(),before);g.mode='playing';g.openUpgrades();const t=g.time;g.tick(.05,{x:1});assert.equal(g.time,t);});
test('seventy-two swords require material, realm and crafted sword before rank eight is offered',()=>{const g=game();g.player.weapons.sword=7;g.player.spirit=999;g.player.materials.gold=2;g.currentEvent=g.pois.find(p=>p.kind==='forge').id;g.mode='event';assert.ok(g.eventOptions().find(o=>o.id==='awaken').disabled);g.regionIndex=2;g.player.level=25;g.player.swordCrafted=true;assert.equal(g.eventOptions().find(o=>o.id==='awaken').disabled,false);g.chooseEvent('awaken');assert.equal(g.player.materials.gold,1);assert.equal(g.player.swordAwakened,true);});
test('portal requires both boss defeat and region duration',()=>{const g=game();g.regionTime=400;assert.equal(g.completeRegion(),false);g.bossDead=true;g.regionTime=200;assert.equal(g.completeRegion(),false);g.regionTime=360;assert.equal(g.completeRegion(),true);assert.equal(g.mode,'transition');g.nextRegion();assert.equal(g.regionIndex,1);assert.equal(g.regionTime,0);assert.equal(g.projectiles.length,0);});
test('consumable count and shield absorption are real and finite',()=>{const g=game();g.player.consumables.shield=1;assert.equal(useConsumable(g),true);assert.equal(g.player.shield,60);assert.equal(g.player.consumables.shield,0);assert.equal(useConsumable(g),false);g.hurt(70);assert.equal(g.player.shield,0);assert.equal(g.player.hp,100);});
test('hostile save data fails version and range checks',()=>{for(const text of ['{}','null','{"version":2,"character":"oops"}',JSON.stringify({...JSON.parse(game().save()),time:1e20})])assert.throws(()=>BattleCore.load(text));});

test('distant XP stays on its ground and a collected vacuum gathers it',()=>{const g=game(),p=g.player;g.pickups=[{id:100,x:p.x+420,y:p.y,value:7,kind:'xp',age:0}];for(let i=0;i<700;i++)g.updateWorld(.05);assert.equal(g.pickups[0].x,p.x+420);assert.equal(p.xp,0);g.pickups.push({id:101,x:p.x,y:p.y,value:9,kind:'vacuum',age:0});for(let i=0;i<80;i++)g.updateWorld(.05);assert.equal(g.pickups.length,0);assert.equal(p.xp,16);});
test('XP batching conserves value and leaves distant drops away from the player',()=>{const g=game();g.pickups=Array.from({length:620},(_,i)=>({id:1000+i,x:350+i%20,y:300+Math.floor(i/20),value:2,kind:'xp',age:0}));g.updateWorld(.01);assert.equal(g.pickups.reduce((n,q)=>n+q.value,0),1240);assert.equal(g.player.xp,0);assert.ok(g.pickups.length<620);});
test('timed elite persists across a save and cannot be farmed by reloading',()=>{const g=game();g.regionTime=76;g.updateEncounters(.2);assert.equal(g.enemies.filter(e=>e.elite).length,1);const loaded=BattleCore.load(g.save());loaded.enemies=[];loaded.spawnTimer=0;loaded.updateEncounters(.2);assert.equal(loaded.enemies.length,0);loaded.regionTime=400;loaded.updateEncounters(1);assert.equal(loaded.enemies.length,0);});

test('exploration streams nearby landmarks and retains looted state after returning and loading',()=>{const g=game(),chest=g.pois.find(q=>q.kind==='chest');chest.state='done';const key=chest.recordKey;g.player.x=8900;g.player.y=-8700;g.streamPOIs();assert.ok(g.pois.some(q=>Math.hypot(q.x-g.player.x,q.y-g.player.y)<900));assert.ok(g.pois.length<=72);const loaded=BattleCore.load(g.save());loaded.player.x=0;loaded.player.y=510;loaded.streamPOIs();assert.equal(loaded.pois.find(q=>q.recordKey===key).state,'done');});
test('boss appears near the current explored chunk rather than at the world origin',()=>{const g=game();g.player.x=8900;g.player.y=9200;g.regionTime=g.region.bossAt;g.tick(.02,{});const boss=g.enemies.find(e=>e.boss);assert.ok(boss);assert.ok(Math.hypot(boss.x-g.player.x,boss.y-g.player.y)<1700);assert.ok(Math.abs(boss.x)>6000);});
